/*
    The code is automatically generated by the genBind tool.
    Author: ying32
    https://github.com/ying32
*/

#![allow(non_snake_case)]
#![allow(improper_ctypes)]
#![allow(non_camel_case_types)]
#![allow(dead_code)]
#![allow(non_upper_case_globals)]


use std::os::raw::c_char;


#[repr(C)]
pub struct TPoint {
    x: i32,
    y: i32,
}


#[repr(C)]
pub struct TRect {
    left: i32,
    top: i32,
    right: i32,
    bottom: i32,
}


#[repr(C)]
pub struct TSize {
    cx: i32,
    cy: i32,
}

pub type HWND = usize;
pub type HBITMAP = usize;
pub type HMENU = usize;
pub type HICON = usize;
pub type HDC = usize;
pub type HFONT = usize;
pub type HBRUSH = usize;
pub type HPEN = usize;
pub type HKEY = usize;
pub type HMONITOR = usize;
pub type HGDIOBJ = usize;
pub type HMODULE = usize;
pub type COLORREF = u32;
pub type DWORD = u32;
pub type HCURSOR = HICON;
pub type HINST = usize;
pub type LPCWSTR = usize;
pub type HRGN = usize;
pub type UINT = u32;
pub type LPARAM = usize;
pub type WPARAM = usize;
pub type LRESULT = usize;
pub type HResult = usize;
pub type HPALETTE = usize;
pub type HRSRC = usize;
pub type HGLOBAL = usize;
pub type TFNWndEnumProc = usize;
pub type TXID = u64;
pub type ATOM = u16;
pub type TAtom = u16;
pub type SIZE_T = usize;
pub type TSet = u32;

#[repr(C)]
pub struct TMsg {
    hwnd: HWND,
    message: u32,
    wParam: usize,
    lParam: usize,
    time: u32,
    pt: TPoint,
}


#[repr(C)]
pub struct TCursorInfo {
    cbSize: u32,
    flags: u32,
    hCursor: HCURSOR,
    ptScreenPos: TPoint,
}


#[repr(C)]
pub struct TWndClass {
    style: u32,
    lpfnWndProc: usize,
    cbClsExtra: i32,
    cbWndExtra: i32,
    hInstance: usize,
    hIcon: HICON,
    hCursor: HCURSOR,
    hbrBackground: HBRUSH,
    lpszMenuName: LPCWSTR,
    lpszClassName: LPCWSTR,
}

pub type TModalResult = i32;
pub type TColor = u32;
pub type THelpEventData = usize;
pub type TTabOrder = i16;
pub type PFNLVCOMPARE = usize;
pub type PFNTVCOMPARE = usize;
pub type Integer = i32;
pub type Cardinal = u32;
pub type Single = f32;
pub type Word = u16;
pub type Byte = u8;
pub type TFontCharset = u8;
pub type TSpacingSize = i32;
pub type Char = u16;
pub type TClass = usize;
pub type TThreadID = usize;

#[repr(C)]
pub struct TGridCoord {
    x: i32,
    y: i32,
}

pub type TCustomData = usize;
pub type TGridRect = TRect;
pub type IObjectArray = usize;

#[repr(C)]
pub struct TSysLocale {
    defaultLCID: i32,
    priLangID: i32,
    subLangID: i32,
    farEast: bool,
    middleEast: bool,
}


#[repr(C)]
pub struct TSmallPoint {
    x: i16,
    y: i16,
}


#[repr(C)]
pub struct TGUID {
    d1: u32,
    d2: u16,
    d3: u16,
    d4: [u8;8],
}


#[repr(C)]
pub struct TLibResource {
    name: *const c_char,
    ptr: usize,
}


#[repr(C)]
pub struct TResItem {
    name: usize,
    value: usize,
}

pub type TConstraintSize = i32;

#[repr(C)]
pub struct TAlignInfo {
    alignList: usize,
    controlIndex: i32,
    align: TAlign,
    scratch: i32,
}



#[repr(C)]
pub enum TAlign {
    alNone,
    alTop,
    alBottom,
    alLeft,
    alRight,
    alClient,
    alCustom,
}

// set of TAlign
pub type TAlignSet = TSet;

#[repr(C)]
pub enum TBorderStyle {
    bsNone,
    bsSingle,
    bsSizeable,
    bsDialog,
    bsToolWindow,
    bsSizeToolWin,
}

pub type TFormBorderStyle = TBorderStyle;

#[repr(C)]
pub enum TFormStyle {
    fsNormal,
    fsMDIChild,
    fsMDIForm,
    fsStayOnTop,
    fsSplash,
    fsSystemStayOnTop,
}

#[repr(C)]
pub enum TPosition {
    poDesigned, // use bounds from the designer (read from stream)
    poDefault, // LCL decision (normally window manager decides)
    poDefaultPosOnly, // designed size and LCL position
    poDefaultSizeOnly, // designed position and LCL size
    poScreenCenter, // center form on screen (depends on DefaultMonitor)
    poDesktopCenter, // center form on desktop (total of all screens)
    poMainFormCenter, // center form on main form (depends on DefaultMonitor)
    poOwnerFormCenter, // center form on owner form (depends on DefaultMonitor)
    poWorkAreaCenter, // center form on working area (depends on DefaultMonitor)
}

pub type TCursor = i16;

#[repr(C)]
pub enum TSeekOrigin {
    soBeginning,
    soCurrent,
    soEnd,
}

#[repr(C)]
pub enum TPixelFormat {
    pfDevice,
    pf1bit,
    pf4bit,
    pf8bit,
    pf15bit,
    pf16bit,
    pf24bit,
    pf32bit,
    pfCustom,
}

#[repr(C)]
pub enum TAlignment {
    taLeftJustify,
    taRightJustify,
    taCenter,
}

pub type TLeftRight = i32;

#[repr(C)]
pub enum TBiDiMode {
    bdLeftToRight,
    bdRightToLeft,
    bdRightToLeftNoAlign,
    bdRightToLeftReadingOnly,
}

#[repr(C)]
pub enum TVerticalAlignment {
    taAlignTop,
    taAlignBottom,
    taVerticalCenter,
}

#[repr(C)]
pub enum TComboBoxStyle {
    csDropDown, // like an TEdit plus a button to drop down the list, default
    csSimple, // like an TEdit plus a TListBox
    csDropDownList, // like TLabel plus a button to drop down the list
    csOwnerDrawFixed, // like csDropDownList, but custom drawn
    csOwnerDrawVariable, // like csDropDownList, but custom drawn and with each item can have another height
    csOwnerDrawEditableFixed, // like csOwnerDrawFixed, but with TEdit
    csOwnerDrawEditableVariable, // like csOwnerDrawVariable, but with TEdit
}

pub type TColorBoxStyle = TComboBoxStyle;

#[repr(C)]
pub enum TWindowState {
    wsNormal,
    wsMinimized,
    wsMaximized,
    wsFullScreen,
}

#[repr(C)]
pub enum TTextLayout {
    tlTop,
    tlCenter,
    tlBottom,
}

#[repr(C)]
pub enum TEllipsisPosition {
    epNone,
    epPathEllipsis,
    epEndEllipsis,
    epWordEllipsis,
}

pub type TLinkAlignment = TAlignment;

#[repr(C)]
pub enum TListBoxStyle {
    lbStandard,
    lbOwnerDrawFixed,
    lbOwnerDrawVariable,
    lbVirtual,
}

#[repr(C)]
pub enum TPopupAlignment {
    paLeft,
    paRight,
    paCenter,
}

#[repr(C)]
pub enum TTrackButton {
    tbRightButton,
    tbLeftButton,
}

#[repr(C)]
pub enum TProgressBarOrientation {
    pbHorizontal,
    pbVertical,
    pbRightToLeft,
    pbTopDown,
}

#[repr(C)]
pub enum TProgressBarStyle {
    pbstNormal,
    pbstMarquee,
}

#[repr(C)]
pub enum TProgressBarState {
    pbsNormal,
    pbsError,
    pbsPaused,
}

#[repr(C)]
pub enum TButtonLayout {
    blGlyphLeft,
    blGlyphRight,
    blGlyphTop,
    blGlyphBottom,
}

#[repr(C)]
pub enum TButtonState {
    bsUp, // button is up
    bsDisabled, // button disabled (grayed)
    bsDown, // button is down
    bsExclusive, // button is the only down in his group
    bsHot, // button is under mouse
}

#[repr(C)]
pub enum TButtonStyle {
    bsAutoDetect,
    bsWin31,
    bsNew,
}

pub type TNumGlyphs = i32;

#[repr(C)]
pub enum TStaticBorderStyle {
    sbsNone,
    sbsSingle,
    sbsSunken,
}

#[repr(C)]
pub enum TFontStyle {
    fsBold,
    fsItalic,
    fsUnderline,
    fsStrikeOut,
}

// set of TFontStyle
pub type TFontStyles = TSet;

#[repr(C)]
pub enum TScrollStyle {
    ssNone,
    ssHorizontal,
    ssVertical,
    ssBoth,
    ssAutoHorizontal,
    ssAutoVertical,
    ssAutoBoth,
}

#[repr(C)]
pub enum TSortType {
    stNone,
    stData,
    stText,
    stBoth,
}

#[repr(C)]
pub enum TListArrangement {
    arAlignBottom,
    arAlignLeft,
    arAlignRight,
    arAlignTop,
    arDefault,
    arSnapToGrid,
}

#[repr(C)]
pub enum TViewStyle {
    vsIcon,
    vsSmallIcon,
    vsList,
    vsReport,
}

#[repr(C)]
pub enum TItemState {
    isNone,
    isCut,
    isDropHilited,
    isFocused,
    isSelected,
    isActivating,
}

// set of TItemState
pub type TItemStates = TSet;

#[repr(C)]
pub enum TItemChange {
    ctText,
    ctImage,
    ctState,
}

#[repr(C)]
pub enum TItemFind {
    ifData,
    ifPartialString,
    ifExactString,
    ifNearest,
}

#[repr(C)]
pub enum TSearchDirection {
    sdLeft,
    sdRight,
    sdAbove,
    sdBelow,
    sdAll,
}

#[repr(C)]
pub enum TListHotTrackStyle {
    htHandPoint,
    htUnderlineCold,
    htUnderlineHot,
}

// set of TListHotTrackStyle
pub type TListHotTrackStyles = TSet;

#[repr(C)]
pub enum TItemRequests {
    irText,
    irImage,
    irParam,
    irState,
    irIndent,
}

#[repr(C)]
pub enum TBrushStyle {
    bsSolid,
    bsClear,
    bsHorizontal,
    bsVertical,
    bsFDiagonal,
    bsBDiagonal,
    bsCross,
    bsDiagCross,
    bsImage,
    bsPattern,
}

#[repr(C)]
pub enum TPenStyle {
    psSolid,
    psDash,
    psDot,
    psDashDot,
    psDashDotDot,
    psinsideFrame,
    psPattern,
    psClear,
}

#[repr(C)]
pub enum TUDBtnType {
    btNext,
    btPrev,
}

#[repr(C)]
pub enum TTabPosition {
    tpTop,
    tpBottom,
    tpLeft,
    tpRight,
}

#[repr(C)]
pub enum TTabStyle {
    tsTabs,
    tsButtons,
    tsFlatButtons,
}

#[repr(C)]
pub enum TFontPitch {
    fpDefault,
    fpVariable,
    fpFixed,
}

#[repr(C)]
pub enum TPenMode {
    pmBlack,
    pmWhite,
    pmNop,
    pmNot,
    pmCopy,
    pmNotCopy,
    pmMergePenNot,
    pmMaskPenNot,
    pmMergeNotPen,
    pmMaskNotPen,
    pmMerge,
    pmNotMerge,
    pmMask,
    pmNotMask,
    pmXor,
    pmNotXor,
}

#[repr(C)]
pub enum TTrackBarOrientation {
    trHorizontal,
    trVertical,
}

#[repr(C)]
pub enum TUDOrientation {
    udHorizontal,
    udVertical,
}

#[repr(C)]
pub enum TFontQuality {
    fqDefault,
    fqDraft,
    fqProof,
    fqNonAntialiased,
    fqAntialiased,
    fqClearType,
    fqClearTypeNatural,
}

#[repr(C)]
pub enum TCloseAction {
    caNone,
    caHide,
    caFree,
    caMinimize,
}

#[repr(C)]
pub enum TBalloonFlags {
    bfNone,
    bfInfo,
    bfWarning,
    bfError,
}

#[repr(C)]
pub enum TMsgDlgType {
    mtWarning,
    mtError,
    mtInformation,
    mtConfirmation,
    mtCustom,
}

#[repr(C)]
pub enum TMsgDlgBtn {
    mbYes,
    mbNo,
    mbOK,
    mbCancel,
    mbAbort,
    mbRetry,
    mbIgnore,
    mbAll,
    mbNoToAll,
    mbYesToAll,
    mbHelp,
    mbClose,
}

// set of TMsgDlgBtn
pub type TMsgDlgButtons = TSet;

#[repr(C)]
pub enum TSysLinkType {
    sltURL,
    sltID,
}

#[repr(C)]
pub enum TStatusPanelStyle {
    psText,
    psOwnerDraw,
}

#[repr(C)]
pub enum TJPEGPerformance {
    jpBestQuality,
    jpBestSpeed,
}

pub type TJPEGPixelFormat = TPixelFormat;

pub type TShortCut = u16;

#[repr(C)]
pub enum TNodeState {
    nsCut,
    nsDropHilite, // = Node.DropTarget
    nsFocused, // = Node.Focused
    nsSelected, // = Node.Selected
    nsMultiSelected, // = Node.MultiSelected
    nsExpanded, // = Node.Expanded
    nsHasChildren, // = Node.HasChildren
    nsDeleting, // = Node.Deleting, set on Destroy
    nsVisible, // = Node.Visible
    nsBound, // bound to a tree, e.g. has Parent or is top lvl node
}

#[repr(C)]
pub enum TNodeAttachMode {
    naAdd, // add as last sibling of Destination
    naAddFirst, // add as first sibling of Destination
    naAddChild, // add as last child of Destination
    naAddChildFirst, // add as first child of Destination
    naInsert, // insert in front of Destination
    naInsertBehind, // insert behind Destination
}

#[repr(C)]
pub enum TAddMode {
    taAddFirst,
    taAdd,
    taInsert,
}

#[repr(C)]
pub enum TMultiSelectStyles {
    msControlSelect,
    msShiftSelect,
    msVisibleOnly,
    msSiblingOnly,
}

// set of TMultiSelectStyles
pub type TMultiSelectStyle = TSet;

#[repr(C)]
pub enum TActionListState {
    asNormal,
    asSuspended,
    asSuspendedEnabled,
}

#[repr(C)]
pub enum TGradientDirection {
    gdHorizontal,
    gdVertical,
}

#[repr(C)]
pub enum TDrawingStyle {
    dSFocus,
    dSSelected,
    dSNormal,
    dSTransparent,
}

#[repr(C)]
pub enum TImageType {
    itImage,
    itMask,
}

#[repr(C)]
pub enum TResType {
    rtBitmap,
    rtCursor,
    rtIcon,
}

#[repr(C)]
pub enum TLoadResource {
    lrDefaultColor,
    lrDefaultSize,
    lrFromFile,
    lrMap3DColors,
    lrTransparent,
    lrMonoChrome,
}

// set of TLoadResource
pub type TLoadResources = TSet;

#[repr(C)]
pub enum TColorDepth {
    cdDefault,
    cdDeviceDependent,
    cd4Bit,
    cd8Bit,
    cd16Bit,
    cd24Bit,
    cd32Bit,
}

#[repr(C)]
pub enum TCheckBoxState {
    cbUnchecked,
    cbChecked,
    cbGrayed,
}

#[repr(C)]
pub enum TToolButtonStyle {
    tbsButton, // button (can be clicked)
    tbsCheck, // check item (click to toggle state, can be grouped)
    tbsDropDown, // button with dropdown button to show a popup menu
    tbsSeparator, // space holder
    tbsDivider, // space holder with line
    tbsButtonDrop, // button with arrow (not separated from each other)
}

#[repr(C)]
pub enum TTBGradientDrawingOption {
    gdoHotTrack,
    gdoGradient,
}

// set of TTBGradientDrawingOption
pub type TTBGradientDrawingOptions = TSet;

#[repr(C)]
pub enum TColorDialogOption {
    cdFullOpen,
    cdPreventFullOpen,
    cdShowHelp,
    cdSolidColor,
    cdAnyColor,
}

// set of TColorDialogOption
pub type TColorDialogOptions = TSet;

#[repr(C)]
pub enum TBorderIcon {
    biSystemMenu,
    biMinimize,
    biMaximize,
    biHelp,
}

// set of TBorderIcon
pub type TBorderIcons = TSet;

#[repr(C)]
pub enum TFontDialogOption {
    fdAnsiOnly,
    fdTrueTypeOnly,
    fdEffects,
    fdFixedPitchOnly,
    fdForceFontExist,
    fdNoFaceSel,
    fdNoOEMFonts,
    fdNoSimulations,
    fdNoSizeSel,
    fdNoStyleSel,
    fdNoVectorFonts,
    fdShowHelp,
    fdWysiwyg,
    fdLimitSize,
    fdScalableOnly,
    fdApplyButton,
}

// set of TFontDialogOption
pub type TFontDialogOptions = TSet;

#[repr(C)]
pub enum TOpenOption {
    ofReadOnly,
    ofOverwritePrompt, // if selected file exists shows a message, that file
    ofHideReadOnly, // hide read only file
    ofNoChangeDir, // do not change current directory
    ofShowHelp, // show a help button
    ofNoValidate,
    ofAllowMultiSelect, // allow multiselection
    ofExtensionDifferent,
    ofPathMustExist, // shows an error message if selected path does not exist
    ofFileMustExist, // shows an error message if selected file does not exist
    ofCreatePrompt,
    ofShareAware,
    ofNoReadOnlyReturn, // do not return filenames that are readonly
    ofNoTestFileCreate,
    ofNoNetworkButton,
    ofNoLongNames,
    ofOldStyleDialog,
    ofNoDereferenceLinks, // do not resolve links while dialog is shown (only on Windows, see OFN_NODEREFERENCELINKS)
    ofNoResolveLinks, // do not resolve links after Execute
    ofEnableIncludeNotify,
    ofEnableSizing, // dialog can be resized, e.g. via the mouse
    ofDontAddToRecent, // do not add the path to the history list
    ofForceShowHidden, // show hidden files
    ofViewDetail, // details are OS and interface dependent
    ofAutoPreview, // details are OS and interface dependent
}

// set of TOpenOption
pub type TOpenOptions = TSet;

#[repr(C)]
pub enum TOpenOptionEx {
    ofExNoPlacesBar,
}

// set of TOpenOptionEx
pub type TOpenOptionsEx = TSet;

#[repr(C)]
pub enum TPrintRange {
    prAllPages,
    prSelection,
    prPageNums,
    prCurrentPage,
}

#[repr(C)]
pub enum TPrintDialogOption {
    poPrintToFile,
    poPageNums,
    poSelection,
    poWarning,
    poHelp,
    poDisablePrintToFile,
    poBeforeBeginDoc,
}

// set of TPrintDialogOption
pub type TPrintDialogOptions = TSet;

#[repr(C)]
pub enum TPageSetupDialogOption {
    psoDefaultMinMargins,
    psoDisableMargins,
    psoDisableOrientation,
    psoDisablePagePainting,
    psoDisablePaper,
    psoDisablePrinter,
    psoMargins,
    psoMinMargins,
    psoShowHelp,
    psoWarning,
    psoNoNetworkButton,
}

// set of TPageSetupDialogOption
pub type TPageSetupDialogOptions = TSet;

#[repr(C)]
pub enum TPrinterKind {
    pkDotMatrix,
    pkHPPCL,
}

#[repr(C)]
pub enum TPageType {
    ptEnvelope,
    ptPaper,
}

#[repr(C)]
pub enum TPageMeasureUnits {
    pmDefault,
    pmMillimeters,
    pmInches,
}

#[repr(C)]
pub enum TStringsOption {
    soStrictDelimiter,
    soWriteBOM,
    soTrailingLineBreak,
    soUseLocale,
}

// set of TStringsOption
pub type TStringsOptions = TSet;

#[repr(C)]
pub enum TShiftStateEnum {
    ssShift,
    ssAlt,
    ssCtrl,
    ssLeft,
    ssRight,
    ssMiddle,
    ssDouble,
    ssMeta,
    ssSuper,
    ssHyper,
    ssAltGr,
    ssCaps,
    ssNum,
    ssScroll,
    ssTriple,
    ssQuad,
    ssExtra1,
    ssExtra2,
}

// set of TShiftStateEnum
pub type TShiftState = TSet;

#[repr(C)]
pub enum TMouseButton {
    mbLeft,
    mbRight,
    mbMiddle,
    mbExtra1,
    mbExtra2,
}

#[repr(C)]
pub enum TFillStyle {
    fsSurface,
    fsBorder,
}

#[repr(C)]
pub enum TFillMode {
    fmAlternate,
    fmWinding,
}

#[repr(C)]
pub enum TCanvasStates {
    csHandleValid,
    csFontValid,
    csPenValid,
    csBrushValid,
    csRegionValid,
}

// set of TCanvasStates
pub type TCanvasState = TSet;

#[repr(C)]
pub enum TCanvasOrientation {
    coLeftToRight,
    coRightToLeft,
}

#[repr(C)]
pub enum TTextFormats {
    tfBottom,
    tfCalcRect,
    tfCenter,
    tfEditControl,
    tfEndEllipsis,
    tfPathEllipsis,
    tfExpandTabs,
    tfExternalLeading,
    tfLeft,
    tfModifyString,
    tfNoClip,
    tfNoPrefix,
    tfRight,
    tfRtlReading,
    tfSingleLine,
    tfTop,
    tfVerticalCenter,
    tfWordBreak,
    tfHidePrefix,
    tfNoFullWidthCharBreak,
    tfPrefixOnly,
    tfTabStop,
    tfWordEllipsis,
    tfComposited,
}

// set of TTextFormats
pub type TTextFormat = TSet;

#[repr(C)]
pub enum TBevelCut {
    bvNone,
    bvLowered,
    bvRaised,
    bvSpace,
}

#[repr(C)]
pub enum TBevelEdge {
    beLeft,
    beTop,
    beRight,
    beBottom,
}

// set of TBevelEdge
pub type TBevelEdges = TSet;

#[repr(C)]
pub enum TBevelKind {
    bkNone,
    bkTile,
    bkSoft,
    bkFlat,
}

#[repr(C)]
pub enum TTickMark {
    tmBottomRight,
    tmTopLeft,
    tmBoth,
}

#[repr(C)]
pub enum TTickStyle {
    tsNone,
    tsAuto,
    tsManual,
}

#[repr(C)]
pub enum TPositionToolTip {
    ptNone,
    ptTop,
    ptLeft,
    ptBottom,
    ptRight,
}

#[repr(C)]
pub enum TDateTimeKind {
    dtkDate,
    dtkTime,
    dtkDateTime,
}

#[repr(C)]
pub enum TDTDateMode {
    dmComboBox,
    dmUpDown,
    dmNone,
}

#[repr(C)]
pub enum TDTDateFormat {
    dfShort,
    dfLong,
}

#[repr(C)]
pub enum TDTCalAlignment {
    dtaLeft,
    dtaRight,
    dtaDefault,
}

#[repr(C)]
pub enum TCalDayOfWeek {
    dowMonday,
    dowTuesday,
    dowWednesday,
    dowThursday,
    dowFriday,
    dowSaturday,
    dowSunday,
    dowLocaleDefault,
}

#[repr(C)]
pub enum TSearchType {
    stWholeWord,
    stMatchCase,
}

// set of TSearchType
pub type TSearchTypes = TSet;

#[repr(C)]
pub enum TNumberingStyle {
    nsNone,
    nsBullte,
}

#[repr(C)]
pub enum TAttributeType {
    atSelected,
    atDefaultText,
}

#[repr(C)]
pub enum TConsistentAttribute {
    caBold,
    caColor,
    caFace,
    caItalic,
    caSize,
    caStrikeOut,
    caUnderline,
    caProtected,
}

// set of TConsistentAttribute
pub type TConsistentAttributes = TSet;

#[repr(C)]
pub enum TIconArrangement {
    iaTop,
    iaLeft,
}

#[repr(C)]
pub enum THeaderStyle {
    hsGradient,
    hsImage,
    hsThemed,
}

#[repr(C)]
pub enum TImageAlignment {
    iiaLeft,
    iiaRight,
    iiaTop,
    iiaBottom,
    iiaCenter,
}

#[repr(C)]
pub enum TAnchorKind {
    akTop,
    akLeft,
    akRight,
    akBottom,
}

// set of TAnchorKind
pub type TAnchors = TSet;

#[repr(C)]
pub enum TOwnerDrawStateType {
    odSelected,
    odGrayed,
    odDisabled,
    odChecked,
    odFocused,
    odDefault,
    odHotLight,
    odInactive,
    odNoAccel,
    odNoFocusRect,
    odReserved1,
    odReserved2,
    odComboBoxEdit,
    odBackgroundPainted, // item background already painted
}

// set of TOwnerDrawStateType
pub type TOwnerDrawState = TSet;

#[repr(C)]
pub enum TBitBtnKind {
    bkCustom,
    bkOK,
    bkCancel,
    bkHelp,
    bkYes,
    bkNo,
    bkClose,
    bkAbort,
    bkRetry,
    bkIgnore,
    bkAll,
    bkNoToAll,
    bkYesToAll,
}

#[repr(C)]
pub enum TScrollBarKind {
    sbHorizontal,
    sbVertical,
}

pub type TScrollBarInc = i16;

#[repr(C)]
pub enum TScrollBarStyle {
    ssRegular,
    ssFlat,
    ssHotTrack,
}

#[repr(C)]
pub enum TShapeType {
    stRectangle,
    stSquare,
    stRoundRect,
    stRoundSquare,
    stEllipse,
    stCircle,
    stSquaredDiamond,
    stDiamond,
    stTriangle,
    stTriangleLeft,
    stTriangleRight,
    stTriangleDown,
    stStar,
    stStarDown,
}

pub type TBevelStyle = i32;

#[repr(C)]
pub enum TBevelShape {
    bsBox,
    bsFrame,
    bsTopLine,
    bsBottomLine,
    bsLeftLine,
    bsRightLine,
    bsSpacer,
}

#[repr(C)]
pub enum TGaugeKind {
    gkText,
    gkHorizontalBar,
    gkVerticalBar,
    gkPie,
    gkNeedle,
    gkHalfPie,
}

#[repr(C)]
pub enum TCustomDrawTarget {
    dtControl,
    dtItem,
    dtSubItem,
}

#[repr(C)]
pub enum TCustomDrawStage {
    cdPrePaint,
    cdPostPaint,
    cdPreErase,
    cdPostErase,
}

#[repr(C)]
pub enum TCustomDrawStateFlag {
    cdsSelected,
    cdsGrayed,
    cdsDisabled,
    cdsChecked,
    cdsFocused,
    cdsDefault,
    cdsHot,
    cdsMarked,
    cdsIndeterminate,
}

// set of TCustomDrawStateFlag
pub type TCustomDrawState = TSet;

#[repr(C)]
pub enum TDisplayCode {
    drBounds,
    drIcon,
    drLabel,
    drSelectBounds,
}

#[repr(C)]
pub enum TSelectDirOpt {
    sdAllowCreate,
    sdPerformCreate,
    sdPrompt,
}

// set of TSelectDirOpt
pub type TSelectDirOpts = TSet;

#[repr(C)]
pub enum TFindOption {
    frDown,
    frFindNext,
    frHideMatchCase,
    frHideWholeWord,
    frHideUpDown,
    frMatchCase,
    frDisableMatchCase,
    frDisableUpDown,
    frDisableWholeWord,
    frReplace,
    frReplaceAll,
    frWholeWord,
    frShowHelp,
    frEntireScope,
    frHideEntireScope,
    frPromptOnReplace,
    frHidePromptOnReplace,
    frButtonsAtBottom,
}

// set of TFindOption
pub type TFindOptions = TSet;

#[repr(C)]
pub enum TDragMode {
    dmManual,
    dmAutomatic,
}

#[repr(C)]
pub enum TDragState {
    dsDragEnter,
    dsDragLeave,
    dsDragMove,
}

#[repr(C)]
pub enum TDragKind {
    dkDrag,
    dkDock,
}

#[repr(C)]
pub enum TEditCharCase {
    ecNormal,
    ecUpperCase,
    ecLowerCase,
}

#[repr(C)]
pub enum TEdgeBorder {
    ebLeft,
    ebTop,
    ebRight,
    ebBottom,
}

// set of TEdgeBorder
pub type TEdgeBorders = TSet;

#[repr(C)]
pub enum TEdgeStyle {
    esNone,
    esRaised,
    esLowered,
}

#[repr(C)]
pub enum TGridDrawingStyle {
    gdsClassic,
    gdsThemed,
    gdsGradient,
}

#[repr(C)]
pub enum TGridOption {
    goFixedVertLine,
    goFixedHorzLine,
    goVertLine,
    goHorzLine,
    goRangeSelect,
    goDrawFocusSelected,
    goRowSizing,
    goColSizing,
    goRowMoving,
    goColMoving,
    goEditing,
    goAutoAddRows,
    goTabs,
    goRowSelect,
    goAlwaysShowEditor,
    goThumbTracking,
    goColSpanning, // Enable cellextent calcs
    goRelaxedRowSelect, // User can see focused cell on goRowSelect
    goDblClickAutoSize, // dblclicking columns borders (on hdrs) resize col.
    goSmoothScroll, // Switch scrolling mode (pixel scroll is by default)
    goFixedRowNumbering, // Ya
    goScrollKeepVisible, // keeps focused cell visible while scrolling
    goHeaderHotTracking, // Header cells change look when mouse is over them
    goHeaderPushedLook, // Header cells looks pushed when clicked
    goSelectionActive, // Setting grid.Selection moves also cell cursor
    goFixedColSizing, // Allow to resize fixed columns
    goDontScrollPartCell, // clicking partially visible cells will not scroll
    goCellHints, // show individual cell hints
    goTruncCellHints, // show cell hints if cell text is too long
    goCellEllipsis, // show &#34;...&#34; if cell text is too long
    goAutoAddRowsSkipContentCheck, // BB Also add a row (if AutoAddRows in Options) if last row is empty
    goRowHighlight, // Highlight the current Row
}

// set of TGridOption
pub type TGridOptions = TSet;

#[repr(C)]
pub enum TGridDrawStates {
    gdSelected,
    gdFocused,
    gdFixed,
    gdHot,
    gdPushed,
    gdRowHighlight,
}

// set of TGridDrawStates
pub type TGridDrawState = TSet;

#[repr(C)]
pub enum THeaderSectionStyle {
    hsText,
    hsOwnerDraw,
}

#[repr(C)]
pub enum TLabelPosition {
    lpAbove,
    lpBelow,
    lpLeft,
    lpRight,
}

#[repr(C)]
pub enum TFlowStyle {
    fsLeftRightTopBottom,
    fsRightLeftTopBottom,
    fsLeftRightBottomTop,
    fsRightLeftBottomTop,
    fsTopBottomLeftRight,
    fsBottomTopLeftRight,
    fsTopBottomRightLeft,
    fsBottomTopRightLeft,
}

#[repr(C)]
pub enum TCoolBandMaximize {
    bmNone,
    bmClick,
    bmDblClick,
}

#[repr(C)]
pub enum TMenuBreak {
    mbNone,
    mbBreak,
    mbBarBreak,
}

#[repr(C)]
pub enum TSectionTrackState {
    tsTrackBegin,
    tsTrackMove,
    tsTrackEnd,
}

#[repr(C)]
pub enum TControlStateType {
    csLButtonDown,
    csClicked,
    csPalette,
    csReadingState,
    csFocusing,
    csCreating, // not used, exists for Delphi compatibility
    csPaintCopy,
    csCustomPaint,
    csDestroyingHandle,
    csDocking,
    csVisibleSetInLoading,
}

// set of TControlStateType
pub type TControlState = TSet;

#[repr(C)]
pub enum TControlStyleType {
    csAcceptsControls, // can have children in the designer
    csCaptureMouse, // auto capture mouse when clicked
    csDesignInteractive, // wants mouse events in design mode
    csClickEvents, // handles mouse events
    csFramed, // not implemented, has 3d frame
    csSetCaption, // if Name=Caption, changing the Name changes the Caption
    csOpaque, // the control paints its area completely
    csDoubleClicks, // understands mouse double clicks
    csTripleClicks, // understands mouse triple clicks
    csQuadClicks, // understands mouse quad clicks
    csFixedWidth, // cannot change its width
    csFixedHeight, // cannot change its height (for example combobox)
    csNoDesignVisible, // is invisible in the designer
    csReplicatable, // PaintTo works
    csNoStdEvents, // standard events such as mouse, key, and click events are ignored.
    csDisplayDragImage, // display images from dragimagelist during drag operation over control
    csReflector, // not implemented, the controls respond to size, focus and dlg messages - it can be used as ActiveX control under Windows
    csActionClient, // Action is set
    csMenuEvents, // not implemented
    csNoFocus, // control will not take focus when clicked with mouse.
    csNeedsBorderPaint, // not implemented
    csParentBackground, // tells WinXP to paint the theme background of parent on controls background
    csDesignNoSmoothResize, // when resizing control in the designer do not SetBounds while dragging
    csDesignFixedBounds, // can not be moved nor resized in designer
    csHasDefaultAction, // implements useful ExecuteDefaultAction
    csHasCancelAction, // implements useful ExecuteCancelAction
    csNoDesignSelectable, // can not be selected at design time
    csOwnedChildrenNotSelectable, // child controls owned by this control are NOT selectable in the designer
    csAutoSize0x0, // if the preferred size is 0x0 then control is shrinked ot 0x0
    csAutoSizeKeepChildLeft, // when AutoSize=true do not move children horizontally
    csAutoSizeKeepChildTop, // when AutoSize=true do not move children vertically
    csRequiresKeyboardInput, // If the device has no physical keyboard then show the virtual keyboard when this control gets focus (therefore available only to TWinControl descendents)
}

// set of TControlStyleType
pub type TControlStyle = TSet;

#[repr(C)]
pub enum TMouseActivate {
    maDefault,
    maActivate,
    maActivateAndEat,
    maNoActivate,
    maNoActivateAndEat,
}

#[repr(C)]
pub enum TTaskBarProgressState {
    none,
    indeterminate,
    normal,
    error,
    paused,
}

#[repr(C)]
pub enum TBitmapHandleType {
    bmDIB,
    bmDDB,
}

#[repr(C)]
pub enum TPrinterState {
    psNoDefine,
    psReady,
    psPrinting,
    psStopped,
}

#[repr(C)]
pub enum TPrinterOrientation {
    poPortrait,
    poLandscape,
    poReverseLandscape,
    poReversePortrait,
}

#[repr(C)]
pub enum TPrinterCapability {
    pcCopies,
    pcOrientation,
    pcCollation,
}

// set of TPrinterCapability
pub type TPrinterCapabilities = TSet;

#[repr(C)]
pub enum TPrinterType {
    ptLocal,
    ptNetWork,
}

#[repr(C)]
pub enum TReadyState {
    rsUninitialized,
    rsLoading,
    rsLoaded,
    rsInterActive,
    rsComplete,
}

#[repr(C)]
pub enum TStringEncoding {
    seUnknown,
    seANSI,
    seUnicode,
    seUTF8,
}

#[repr(C)]
pub enum TShowInTaskbar {
    stDefault, // use default rules for showing taskbar item
    stAlways, // always show taskbar item for the form
    stNever, // never show taskbar item for the form
}

#[repr(C)]
pub enum TTaskDialogCommonButton {
    tcbOk,
    tcbYes,
    tcbNo,
    tcbCancel,
    tcbRetry,
    tcbClose,
}

// set of TTaskDialogCommonButton
pub type TTaskDialogCommonButtons = TSet;

#[repr(C)]
pub enum TTaskDialogFlag {
    tfEnableHyperlinks,
    tfUseHiconMain,
    tfUseHiconFooter,
    tfAllowDialogCancellation,
    tfUseCommandLinks,
    tfUseCommandLinksNoIcon,
    tfExpandFooterArea,
    tfExpandedByDefault,
    tfVerificationFlagChecked,
    tfShowProgressBar,
    tfShowMarqueeProgressBar,
    tfCallbackTimer,
    tfPositionRelativeToWindow,
    tfRtlLayout,
    tfNoDefaultRadioButton,
    tfCanBeMinimized,
}

// set of TTaskDialogFlag
pub type TTaskDialogFlags = TSet;

#[repr(C)]
pub enum TTaskDialogIcon {
    tdiNone,
    tdiWarning,
    tdiError,
    tdiInformation,
    tdiShield,
    tdiQuestion,
}

#[repr(C)]
pub enum TComboBoxExStyle {
    csExDropDown,
    csExSimple,
    csExDropDownList,
}

#[repr(C)]
pub enum TComboBoxExStyleEx {
    csExCaseSensitive,
    csExNoEditImage,
    csExNoEditImageIndent,
    csExNoSizeLimit,
    csExPathWordBreak,
}

// set of TComboBoxExStyleEx
pub type TComboBoxExStyles = TSet;

#[repr(C)]
pub enum TAutoCompleteOption {
    acoAutoSuggest,
    acoAutoAppend,
    acoSearch,
    acoFilterPrefixes,
    acoUseTab,
    acoUpDownKeyDropsList,
    acoRtlReading,
}

// set of TAutoCompleteOption
pub type TAutoCompleteOptions = TSet;

#[repr(C)]
pub enum TDefaultMonitor {
    dmDesktop,
    dmPrimary,
    dmMainForm,
    dmActiveForm,
}

#[repr(C)]
pub enum TTransparentMode {
    tmAuto,
    tmFixed,
}

#[repr(C)]
pub enum TDrawImageMode {
    dimNormal,
    dimCenter,
    dimStretch,
}

#[repr(C)]
pub enum TListBoxOption {
    lboDrawFocusRect, // draw focus rect in case of owner drawing
}

// set of TListBoxOption
pub type TListBoxOptions = TSet;

#[repr(C)]
pub enum TAntialiasingMode {
    amDontCare, // default antialiasing
    amOn, // enabled
    amOff, // disabled
}

#[repr(C)]
pub enum TSortDirection {
    sdAscending,
    sdDescending,
}

#[repr(C)]
pub enum TTreeViewExpandSignType {
    tvestTheme, // use themed sign
    tvestPlusMinus, // use +/- sign
    tvestArrow, // use blank arrow
    tvestArrowFill, // use filled arrow
}

#[repr(C)]
pub enum TTreeViewOption {
    tvoAllowMultiselect,
    tvoAutoExpand,
    tvoAutoInsertMark,
    tvoAutoItemHeight,
    tvoHideSelection,
    tvoHotTrack,
    tvoKeepCollapsedNodes,
    tvoReadOnly,
    tvoRightClickSelect,
    tvoRowSelect,
    tvoShowButtons,
    tvoShowLines,
    tvoShowRoot,
    tvoShowSeparators,
    tvoToolTips,
    tvoNoDoubleClickExpand,
    tvoThemedDraw,
}

// set of TTreeViewOption
pub type TTreeViewOptions = TSet;

#[repr(C)]
pub enum TGlyphShowMode {
    gsmAlways, // always show
    gsmNever, // never show
    gsmApplication, // depends on application settings
    gsmSystem, // depends on system settings
}

#[repr(C)]
pub enum TCTabControlOption {
    nboShowCloseButtons,
    nboMultiLine,
    nboHidePageListPopup,
    nboKeyboardTabSwitch,
    nboShowAddTabButton,
    nboDoChangeOnSetIndex,
}

// set of TCTabControlOption
pub type TCTabControlOptions = TSet;

#[repr(C)]
pub enum TAnchorSideReference {
    asrTop,
    asrBottom,
    asrCenter,
}

#[repr(C)]
pub enum TControlCellAlign {
    ccaFill,
    ccaLeftTop,
    ccaRightBottom,
    ccaCenter,
}

// set of TControlCellAlign
pub type TControlCellAligns = TSet;

#[repr(C)]
pub enum TChildControlResizeStyle {
    crsAnchorAligning, // (like Delphi)
    crsScaleChilds, // scale children equally, keep space between children fixed
    crsHomogenousChildResize, // enlarge children equally (i.e. by the same amount of pixel)
    crsHomogenousSpaceResize, // enlarge space between children equally
}

#[repr(C)]
pub enum TControlChildrenLayout {
    cclNone,
    cclLeftToRightThenTopToBottom, // if BiDiMode &lt;&gt; bdLeftToRight then it becomes RightToLeft
    cclTopToBottomThenLeftToRight,
}

#[repr(C)]
pub enum TColumnLayout {
    clHorizontalThenVertical,
    clVerticalThenHorizontal,
}

#[repr(C)]
pub enum TSortIndicator {
    siNone,
    siAscending,
    siDescending,
}

pub type TLibType = i32;

#[repr(C)]
pub enum TColumnButtonStyle {
    cbsAuto,
    cbsEllipsis,
    cbsNone,
    cbsPickList,
    cbsCheckboxColumn,
    cbsButton,
    cbsButtonColumn,
}

#[repr(C)]
pub enum TGridZone {
    gzNormal,
    gzFixedCols,
    gzFixedRows,
    gzFixedCells,
    gzInvalid,
}

// set of TGridZone
pub type TGridZoneSet = TSet;

#[repr(C)]
pub enum TSortOrder {
    soAscending,
    soDescending,
}

#[repr(C)]
pub enum TAutoAdvance {
    aaNone,
    aaDown,
    aaRight,
    aaLeft,
    aaRightDown,
    aaLeftDown,
    aaRightUp,
    aaLeftUp,
}

#[repr(C)]
pub enum TCellHintPriority {
    chpAll,
    chpAllNoDefault,
    chpTruncOnly,
}

#[repr(C)]
pub enum TMouseWheelOption {
    mwCursor,
    mwGrid,
}

#[repr(C)]
pub enum TGridOption2 {
    goScrollToLastCol, // allow scrolling to last column (so that last column can be leftcol)
    goScrollToLastRow, // allow scrolling to last row (so that last row can be toprow)
}

// set of TGridOption2
pub type TGridOptions2 = TSet;

#[repr(C)]
pub enum TRangeSelectMode {
    rsmSingle,
    rsmMulti,
}

#[repr(C)]
pub enum TTitleStyle {
    tsLazarus,
    tsStandard,
    tsNative,
}

#[repr(C)]
pub enum TPrefixOption {
    poNone,
    poHeaderClick,
}


#[cfg(not(target_arch = "x86"))]
#[repr(C)]
struct TDWordFiller {
}


#[cfg(not(target_arch = "x86"))]
#[repr(C)]
pub struct TWMKey {
      msg: u32,
      msgFiller: TDWordFiller,
      charCode: [u16;2],
      charCodeUnusedFiller: TDWordFiller,
      keyData: u32,
      keyDataFiller: TDWordFiller,
      result: usize,
}


#[cfg(not(target_arch = "x86_64"))]
#[repr(C)]
struct TDWordFiller {
      filler: [u8;4],
}


#[cfg(not(target_arch = "x86_64"))]
#[repr(C)]
pub struct TWMKey {
      msg: u32,
      msgFiller: TDWordFiller,
      charCode: [u16;2],
      charCodeUnusedFiller: TDWordFiller,
      keyData: u32,
      keyDataFiller: TDWordFiller,
      result: usize,
}


#[cfg(not(target_arch = "x86"))]
#[repr(C)]
pub struct TMessage {
      msg: u32,
      wParam: WPARAM,
      lParam: LPARAM,
      result: LRESULT,
}


#[cfg(not(target_arch = "x86_64"))]
#[repr(C)]
pub struct TMessage {
      msg: u32,
      _UnusedMsg: u32,
      wParam: WPARAM,
      lParam: LPARAM,
      result: LRESULT,
}

#[cfg(target_os = "linux")]
pub type PGdkWindow = usize;
#[cfg(target_os = "linux")]
pub type TXId = usize;
#[cfg(target_os = "linux")]
pub type PGtkFixed = usize;


#[cfg(target_os = "macos")]
pub type MyNSWindow = usize;



// fn (sender: pointer)
pub type TNotifyEvent = fn(usize);

// fn (sender: pointer, button: TUDBtnType)
pub type TUDClickEvent = fn(usize, TUDBtnType);

// fn (sender: pointer, *mut action: TCloseAction)
pub type TCloseEvent = fn(usize, *mut TCloseAction);

// fn (sender: pointer, *mut canClose: bool)
pub type TCloseQueryEvent = fn(usize, *mut bool);

// fn (sender: pointer, *mut source: pointer, rebuild: bool)
pub type TMenuChangeEvent = fn(usize, *mut usize, bool);

// fn (sender: pointer, link: *const c_char, linkType: TSysLinkType)
pub type TSysLinkEvent = fn(usize, *const c_char, TSysLinkType);

// fn (sender: pointer, *mut e: pointer)
pub type TExceptionEvent = fn(usize, *mut usize);

// fn (sender: pointer, *mut key: Char, shift: TShiftState)
pub type TKeyEvent = fn(usize, *mut Char, TShiftState);

// fn (sender: pointer, *mut key: Char)
pub type TKeyPressEvent = fn(usize, *mut Char);

// fn (sender: pointer, button: TMouseButton, shift: TShiftState, x: i32, y: i32)
pub type TMouseEvent = fn(usize, TMouseButton, TShiftState, i32, i32);

// fn (sender: pointer, shift: TShiftState, x: i32, y: i32)
pub type TMouseMoveEvent = fn(usize, TShiftState, i32, i32);

// fn (sender: pointer, shift: TShiftState, wheelDelta: i32, x: i32, y: i32, *mut handled: bool)
pub type TMouseWheelEvent = fn(usize, TShiftState, i32, i32, i32, *mut bool);

// fn (control: pointer, index: i32, *mut aRect: TRect, state: TOwnerDrawState)
pub type TDrawItemEvent = fn(usize, i32, *mut TRect, TOwnerDrawState);

// fn (sender: pointer, *mut aCanvas: pointer, *mut aRect: TRect, selected: bool)
pub type TMenuDrawItemEvent = fn(usize, *mut usize, *mut TRect, bool);

// fn (sender: pointer, *mut column: pointer)
pub type TLVColumnClickEvent = fn(usize, *mut usize);

// fn (sender: pointer, *mut column: pointer, *mut point: TPoint)
pub type TLVColumnRClickEvent = fn(usize, *mut usize, *mut TPoint);

// fn (sender: pointer, *mut item: pointer, selected: bool)
pub type TLVSelectItemEvent = fn(usize, *mut usize, bool);

// fn (sender: pointer, *mut item: pointer)
pub type TLVCheckedItemEvent = fn(usize, *mut usize);

// fn (sender: pointer, *mut item1: pointer, *mut item2: pointer, data: i32, *mut compare: i32)
pub type TLVCompareEvent = fn(usize, *mut usize, *mut usize, i32, *mut i32);

// fn (sender: pointer, *mut item: pointer, change: TItemChange)
pub type TLVChangeEvent = fn(usize, *mut usize, TItemChange);

// fn (sender: pointer, *mut item: pointer)
pub type TLVNotifyEvent = fn(usize, *mut usize);

// fn (*mut sender: pointer, *mut aRect: TRect, stage: TCustomDrawStage, *mut defaultDraw: bool)
pub type TLVAdvancedCustomDrawEvent = fn(*mut usize, *mut TRect, TCustomDrawStage, *mut bool);

// fn (*mut sender: pointer, *mut item: pointer, state: TCustomDrawState, Stage: TCustomDrawStage, *mut defaultDraw: bool)
pub type TLVAdvancedCustomDrawItemEvent = fn(*mut usize, *mut usize, TCustomDrawState, TCustomDrawStage, *mut bool);

// fn (*mut sender: pointer, *mut item: pointer, subItem: i32, state: TCustomDrawState, stage: TCustomDrawStage, *mut defaultDraw: bool)
pub type TLVAdvancedCustomDrawSubItemEvent = fn(*mut usize, *mut usize, i32, TCustomDrawState, TCustomDrawStage, *mut bool);

// fn (sender: pointer, *mut node1: pointer, *mut node2: pointer, data: i32, *mut compare: i32)
pub type TTVCompareEvent = fn(usize, *mut usize, *mut usize, i32, *mut i32);

// fn (sender: pointer, *mut node: pointer)
pub type TTVExpandedEvent = fn(usize, *mut usize);

// fn (sender: pointer, *mut node: pointer)
pub type TTVChangedEvent = fn(usize, *mut usize);

// fn (*mut sender: pointer, *mut aRect: TRect, stage: TCustomDrawStage, *mut defaultDraw: bool)
pub type TTVAdvancedCustomDrawEvent = fn(*mut usize, *mut TRect, TCustomDrawStage, *mut bool);

// fn (*mut sender: pointer, *mut node: pointer, state: TCustomDrawState, stage: TCustomDrawStage, *mut paintImages: bool, *mut defaultDraw: bool)
pub type TTVAdvancedCustomDrawItemEvent = fn(*mut usize, *mut usize, TCustomDrawState, TCustomDrawStage, *mut bool, *mut bool);

// fn (sender: pointer, tabIndex: i32, *mut imageIndex: i32)
pub type TTabGetImageEvent = fn(usize, i32, *mut i32);

// fn (*mut sender: pointer, *mut aRect: TRect, stage: TCustomDrawStage, *mut defaultDraw: bool)
pub type TTBAdvancedCustomDrawEvent = fn(*mut usize, *mut TRect, TCustomDrawStage, *mut bool);

// fn ()
pub type TThreadProc = fn();

// fn (sender: pointer, aFileNames: usize, len: isize)
pub type TDropFilesEvent = fn(usize, usize, isize);

// fn (sender: pointer, *mut minWidth: i32, *mut minHeight: i32, *mut maxWidth: i32, *mut maxHeight: i32)
pub type TConstrainedResizeEvent = fn(usize, *mut i32, *mut i32, *mut i32, *mut i32);

// fn (command: u16, data: THelpEventData, *mut callhelp: bool, *mut result: bool)
pub type THelpEvent = fn(u16, THelpEventData, *mut bool, *mut bool);

// fn (*mut msg: TWMKey, *mut handled: bool)
pub type TShortCutEvent = fn(*mut TWMKey, *mut bool);

// fn (sender: pointer, *mut mousePos: TPoint, *mut handled: bool)
pub type TContextPopupEvent = fn(usize, *mut TPoint, *mut bool);

// fn (sender: pointer, source: pointer, x: i32, y: i32, state: TDragState, *mut accept: bool)
pub type TDragOverEvent = fn(usize, usize, i32, i32, TDragState, *mut bool);

// fn (sender: pointer, source: pointer, x: i32, y: i32)
pub type TDragDropEvent = fn(usize, usize, i32, i32);

// fn (sender: pointer, target: pointer, x: i32, y: i32)
pub type TEndDragEvent = fn(usize, usize, i32, i32);

// fn (sender: pointer, *mut source: pointer, x: i32, y: i32)
pub type TDockDropEvent = fn(usize, *mut usize, i32, i32);

// fn (sender: pointer, *mut source: pointer, x: i32, y: i32, state: TDragState, *mut accept: bool)
pub type TDockOverEvent = fn(usize, *mut usize, i32, i32, TDragState, *mut bool);

// fn (sender: pointer, *mut client: pointer, *mut newTarget: pointer, *mut allow: bool)
pub type TUnDockEvent = fn(usize, *mut usize, *mut usize, *mut bool);

// fn (sender: pointer, *mut dragObject: pointer)
pub type TStartDockEvent = fn(usize, *mut usize);

// fn (sender: pointer, *mut dockClient: pointer, *mut influenceRect: TRect, *mut mousePos: TPoint, *mut canDock: bool)
pub type TGetSiteInfoEvent = fn(usize, *mut usize, *mut TRect, *mut TPoint, *mut bool);

// fn (sender: pointer, shift: TShiftState, *mut mousePos: TPoint, *mut handled: bool)
pub type TMouseWheelUpDownEvent = fn(usize, TShiftState, *mut TPoint, *mut bool);

// fn (sender: pointer, isColumn: bool, sIndex: i32, tIndex: i32)
pub type TGridOperationEvent = fn(usize, bool, i32, i32);

// fn (sender: pointer, aCol: i32, aRow: i32, *mut aRect: TRect, state: TGridDrawState)
pub type TDrawCellEvent = fn(usize, i32, i32, *mut TRect, TGridDrawState);

// fn (sender: pointer, aCol: i32, aRow: i32)
pub type TFixedCellClickEvent = fn(usize, i32, i32);

// fn (sender: pointer, aCol: i32, aRow: i32, *mut value: *const c_char)
pub type TGetEditEvent = fn(usize, i32, i32, *mut *const c_char);

// fn (sender: pointer, aCol: i32, aRow: i32, *mut canSelect: bool)
pub type TSelectCellEvent = fn(usize, i32, i32, *mut bool);

// fn (sender: pointer, aCol: i32, aRow: i32, value: *const c_char)
pub type TSetEditEvent = fn(usize, i32, i32, *const c_char);

// fn (*mut headerControl: pointer, *mut section: pointer, *mut aRect: TRect, pressed: bool)
pub type TDrawSectionEvent = fn(*mut usize, *mut usize, *mut TRect, bool);

// fn (*mut headerControl: pointer, *mut section: pointer)
pub type TSectionNotifyEvent = fn(*mut usize, *mut usize);

// fn (*mut headerControl: pointer, *mut section: pointer, width: i32, state: TSectionTrackState)
pub type TSectionTrackEvent = fn(*mut usize, *mut usize, i32, TSectionTrackState);

// fn (sender: pointer, *mut fromSection: pointer, *mut toSection: pointer, *mut allowDrag: bool)
pub type TSectionDragEvent = fn(usize, *mut usize, *mut usize, *mut bool);

// fn (*mut headerControl: pointer, *mut section: pointer)
pub type TCustomSectionNotifyEvent = fn(*mut usize, *mut usize);

// fn (sender: pointer, button: TMouseButton, shift: TShiftState, x: i32, y: i32, hitTest: i32, *mut mouseActivate: TMouseActivate)
pub type TMouseActivateEvent = fn(usize, TMouseButton, TShiftState, i32, i32, i32, *mut TMouseActivate);

// fn (*mut control: pointer, index: i32, *mut data: *const c_char)
pub type TLBGetDataEvent = fn(*mut usize, i32, *mut *const c_char);

// fn (*mut control: pointer, index: i32, dataObject: pointer)
pub type TLBGetDataObjectEvent = fn(*mut usize, i32, usize);

// fn (*mut control: pointer, findString: *const c_char, result: i32)
pub type TLBFindDataEvent = fn(*mut usize, *const c_char, i32);

// fn (*mut control: pointer, index: i32, *mut height: i32)
pub type TMeasureItemEvent = fn(*mut usize, i32, *mut i32);

// fn (sender: pointer, *mut item: pointer, change: TItemChange, *mut allowChange: bool)
pub type TLVChangingEvent = fn(usize, *mut usize, TItemChange, *mut bool);

// fn (sender: pointer, *mut item: pointer)
pub type TLVOwnerDataEvent = fn(usize, *mut usize);

// fn (sender: pointer, find: TItemFind, findString: *const c_char, *mut findPosition: TPoint, findData: TCustomData, startIndex: i32, direction: TSearchDirection, warp: bool, *mut index: i32)
pub type TLVOwnerDataFindEvent = fn(usize, TItemFind, *const c_char, *mut TPoint, TCustomData, i32, TSearchDirection, bool, *mut i32);

// fn (sender: pointer, *mut item: pointer)
pub type TLVDeletedEvent = fn(usize, *mut usize);

// fn (sender: pointer, *mut item: pointer, *mut allowEdit: bool)
pub type TLVEditingEvent = fn(usize, *mut usize, *mut bool);

// fn (sender: pointer, *mut item: pointer, *mut s: *const c_char)
pub type TLVEditedEvent = fn(usize, *mut usize, *mut *const c_char);

// fn (sender: pointer, *mut aCanvas: pointer, *mut width: i32, *mut height: i32)
pub type TMenuMeasureItemEvent = fn(usize, *mut usize, *mut i32, *mut i32);

// fn (sender: pointer, *mut allowChange: bool)
pub type TTabChangingEvent = fn(usize, *mut bool);

// fn (sender: pointer, *mut node: pointer, *mut allowChange: bool)
pub type TTVChangingEvent = fn(usize, *mut usize, *mut bool);

// fn (sender: pointer, *mut node: pointer, *mut allowCollapse: bool)
pub type TTVCollapsingEvent = fn(usize, *mut usize, *mut bool);

// fn (sender: pointer, *mut node: pointer, *mut s: *const c_char)
pub type TTVEditedEvent = fn(usize, *mut usize, *mut *const c_char);

// fn (sender: pointer, *mut node: pointer, *mut allowEdit: bool)
pub type TTVEditingEvent = fn(usize, *mut usize, *mut bool);

// fn (sender: pointer, *mut node: pointer, *mut allowExpansion: bool)
pub type TTVExpandingEvent = fn(usize, *mut usize, *mut bool);

// fn (sender: pointer, *mut node: pointer, *mut hint: *const c_char)
pub type TTVHintEvent = fn(usize, *mut usize, *mut *const c_char);

// fn (sender: pointer, *mut allowChange: bool)
pub type TUDChangingEvent = fn(usize, *mut bool);

// fn (sender: pointer, winErrorCode: u32, errorDescription: *const c_char, *mut handled: bool)
pub type TCreatingListErrorEvent = fn(usize, u32, *const c_char, *mut bool);

// fn (*mut sender: pointer, *mut aRect: TRect, *mut defaultDraw: bool)
pub type TLVCustomDrawEvent = fn(*mut usize, *mut TRect, *mut bool);

// fn (*mut sender: pointer, *mut item: pointer, state: TCustomDrawStage, *mut defaultDraw: bool)
pub type TLVCustomDrawItemEvent = fn(*mut usize, *mut usize, TCustomDrawStage, *mut bool);

// fn (*mut sender: pointer, *mut item: pointer, subItem: i32, state: TCustomDrawStage, *mut defaultDraw: bool)
pub type TLVCustomDrawSubItemEvent = fn(*mut usize, *mut usize, i32, TCustomDrawStage, *mut bool);

// fn (*mut sender: pointer, *mut item: pointer, *mut rect: TRect, state: TOwnerDrawState)
pub type TLVDrawItemEvent = fn(*mut usize, *mut usize, *mut TRect, TOwnerDrawState);

// fn (sender: pointer, startIndex: i32, endIndex: i32)
pub type TLVDataHintEvent = fn(usize, i32, i32);

pub type TLVOwnerDataHintEvent = TLVDataHintEvent;

// fn (*mut sender: pointer, *mut aRect: TRect, *mut defaultDraw: bool)
pub type TTVCustomDrawEvent = fn(*mut usize, *mut TRect, *mut bool);

// fn (*mut sender: pointer, *mut node: pointer, state: TCustomDrawStage, *mut defaultDraw: bool)
pub type TTVCustomDrawItemEvent = fn(*mut usize, *mut usize, TCustomDrawStage, *mut bool);

// fn (*mut msg: TMessage)
pub type TWndProcEvent = fn(*mut TMessage);

// fn (sender: pointer, text: *const c_char)
pub type TWebTitleChangeEvent = fn(usize, *const c_char);

// fn (sender: pointer, funcName: *const c_char, args: *const c_char, *mut retVal: *const c_char)
pub type TWebJSExternalEvent = fn(usize, *const c_char, *const c_char, *mut *const c_char);

// fn (sender: pointer, modalResult: TModalResult, *mut canClose: bool)
pub type TTaskDlgClickEvent = fn(usize, TModalResult, *mut bool);

// fn (sender: pointer, tickCount: u32, *mut reset: bool)
pub type TTaskDlgTimerEvent = fn(usize, u32, *mut bool);

// fn (*mut sender: pointer, *mut control: pointer, *mut newLeft: i32, *mut newTop: i32, *mut newWidth: i32, *mut newHeight: i32, *mut alignRect: TRect, alignInfo: TAlignInfo)
pub type TAlignPositionEvent = fn(*mut usize, *mut usize, *mut i32, *mut i32, *mut i32, *mut i32, *mut TRect, TAlignInfo);

// fn (sender: pointer, index: i32)
pub type TCheckGroupClicked = fn(usize, i32);

// fn (sender: pointer, aCol: i32, aRow: i32)
pub type TOnSelectEvent = fn(usize, i32, i32);

// fn (sender: pointer, aCol: i32, aRow: i32, aState: TCheckBoxState)
pub type TToggledCheckboxEvent = fn(usize, i32, i32, TCheckBoxState);

// fn (sender: pointer, ACol: i32, ARow: i32, BCol: i32, BRow: i32, *mut result: i32)
pub type TOnCompareCells = fn(usize, i32, i32, i32, i32, *mut i32);

// fn (sender: pointer, ACol: i32, ARow: i32, *mut hintText: *const c_char)
pub type TGetCellHintEvent = fn(usize, i32, i32, *mut *const c_char);

// fn (sender: pointer, ACol: i32, ARow: i32, *mut value: TCheckBoxState)
pub type TGetCheckboxStateEvent = fn(usize, i32, i32, *mut TCheckBoxState);

// fn (sender: pointer, ACol: i32, ARow: i32, Value: TCheckBoxState)
pub type TSetCheckboxStateEvent = fn(usize, i32, i32, TCheckBoxState);

// fn (sender: pointer, isColumn: bool, index: i32)
pub type THdrEvent = fn(usize, bool, i32);

// fn (sender: pointer, isColumn: bool, aIndex: i32, aSize: i32)
pub type THeaderSizingEvent = fn(usize, bool, i32, i32);

// fn (sender: pointer, aCol: i32, aRow: i32, *mut editor: pointer)
pub type TSelectEditorEvent = fn(usize, i32, i32, *mut usize);

// fn (sender: pointer, aCol: i32, aRow: i32, CheckedState: TCheckBoxState, *mut aBitmap: pointer)
pub type TUserCheckBoxBitmapEvent = fn(usize, i32, i32, TCheckBoxState, *mut usize);

// fn (sender: pointer, aCol: i32, aRow: i32, oldValue: *const c_char, *mut newValue: *const c_char)
pub type TValidateEntryEvent = fn(usize, i32, i32, *const c_char, *mut *const c_char);


// Delphi中的颜色表，Delphi中的TColor与一般HTML的RGB有点不一样，反过来的以BGR表示.
const clClSysNone: TColor = 0x1FFFFFFF;
const clSysDefault: TColor = 0x20000000;

// Actual colors
const clAliceblue: TColor = 0xFFF8F0;
const clAntiquewhite: TColor = 0xD7EBFA;
const clAqua: TColor = 0xFFFF00;
const clAquamarine: TColor = 0xD4FF7F;
const clAzure: TColor = 0xFFFFF0;
const clBeige: TColor = 0xDCF5F5;
const clBisque: TColor = 0xC4E4FF;
const clBlack: TColor = 0x000000;
const clBlanchedalmond: TColor = 0xCDEBFF;
const clBlue: TColor = 0xFF0000;
const clBlueviolet: TColor = 0xE22B8A;
const clBrown: TColor = 0x2A2AA5;
const clBurlywood: TColor = 0x87B8DE;
const clCadetblue: TColor = 0xA09E5F;
const clChartreuse: TColor = 0x00FF7F;
const clChocolate: TColor = 0x1E69D2;
const clCoral: TColor = 0x507FFF;
const clCornflowerblue: TColor = 0xED9564;
const clCornsilk: TColor = 0xDCF8FF;
const clCrimson: TColor = 0x3C14DC;
const clCyan: TColor = 0xFFFF00;
const clDarkblue: TColor = 0x8B0000;
const clDarkcyan: TColor = 0x8B8B00;
const clDarkgoldenrod: TColor = 0x0B86B8;
const clDarkgray: TColor = 0xA9A9A9;
const clDarkgreen: TColor = 0x006400;
const clDarkgrey: TColor = 0xA9A9A9;
const clDarkkhaki: TColor = 0x6BB7BD;
const clDarkmagenta: TColor = 0x8B008B;
const clDarkolivegreen: TColor = 0x2F6B55;
const clDarkorange: TColor = 0x008CFF;
const clDarkorchid: TColor = 0xCC3299;
const clDarkred: TColor = 0x00008B;
const clDarksalmon: TColor = 0x7A96E9;
const clDarkseagreen: TColor = 0x8FBC8F;
const clDarkslateblue: TColor = 0x8B3D48;
const clDarkslategray: TColor = 0x4F4F2F;
const clDarkslategrey: TColor = 0x4F4F2F;
const clDarkturquoise: TColor = 0xD1CE00;
const clDarkviolet: TColor = 0xD30094;
const clDeeppink: TColor = 0x9314FF;
const clDeepskyblue: TColor = 0xFFBF00;
const clDimgray: TColor = 0x696969;
const clDimgrey: TColor = 0x696969;
const clDodgerblue: TColor = 0xFF901E;
const clFirebrick: TColor = 0x2222B2;
const clFloralwhite: TColor = 0xF0FAFF;
const clForestgreen: TColor = 0x228B22;
const clFuchsia: TColor = 0xFF00FF;
const clGainsboro: TColor = 0xDCDCDC;
const clGhostwhite: TColor = 0xFFF8F8;
const clGold: TColor = 0x00D7FF;
const clGoldenrod: TColor = 0x20A5DA;
const clGray: TColor = 0x808080;
const clGreen: TColor = 0x008000;
const clGreenyellow: TColor = 0x2FFFAD;
const clGrey: TColor = 0x808080;
const clHoneydew: TColor = 0xF0FFF0;
const clHotpink: TColor = 0xB469FF;
const clIndianred: TColor = 0x5C5CCD;
const clIndigo: TColor = 0x82004B;
const clIvory: TColor = 0xF0FFFF;
const clKhaki: TColor = 0x8CE6F0;
const clLavender: TColor = 0xFAE6E6;
const clLavenderblush: TColor = 0xF5F0FF;
const clLawngreen: TColor = 0x00FC7C;
const clLemonchiffon: TColor = 0xCDFAFF;
const clLightblue: TColor = 0xE6D8AD;
const clLightcoral: TColor = 0x8080F0;
const clLightcyan: TColor = 0xFFFFE0;
const clLightgoldenrodyellow: TColor = 0xD2FAFA;
const clLightgray: TColor = 0xD3D3D3;
const clLightgreen: TColor = 0x90EE90;
const clLightgrey: TColor = 0xD3D3D3;
const clLightpink: TColor = 0xC1B6FF;
const clLightsalmon: TColor = 0x7AA0FF;
const clLightseagreen: TColor = 0xAAB220;
const clLightskyblue: TColor = 0xFACE87;
const clLightslategray: TColor = 0x998877;
const clLightslategrey: TColor = 0x998877;
const clLightsteelblue: TColor = 0xDEC4B0;
const clLightyellow: TColor = 0xE0FFFF;
const clLtGray: TColor = 0xC0C0C0;
const clMedGray: TColor = 0xA4A0A0;
const clDkGray: TColor = 0x808080;
const clMoneyGreen: TColor = 0xC0DCC0;
const clLegacySkyBlue: TColor = 0xF0CAA6;
const clCream: TColor = 0xF0FBFF;
const clLime: TColor = 0x00FF00;
const clLimegreen: TColor = 0x32CD32;
const clLinen: TColor = 0xE6F0FA;
const clMagenta: TColor = 0xFF00FF;
const clMaroon: TColor = 0x000080;
const clMediumaquamarine: TColor = 0xAACD66;
const clMediumblue: TColor = 0xCD0000;
const clMediumorchid: TColor = 0xD355BA;
const clMediumpurple: TColor = 0xDB7093;
const clMediumseagreen: TColor = 0x71B33C;
const clMediumslateblue: TColor = 0xEE687B;
const clMediumspringgreen: TColor = 0x9AFA00;
const clMediumturquoise: TColor = 0xCCD148;
const clMediumvioletred: TColor = 0x8515C7;
const clMidnightblue: TColor = 0x701919;
const clMintcream: TColor = 0xFAFFF5;
const clMistyrose: TColor = 0xE1E4FF;
const clMoccasin: TColor = 0xB5E4FF;
const clNavajowhite: TColor = 0xADDEFF;
const clNavy: TColor = 0x800000;
const clOldlace: TColor = 0xE6F5FD;
const clOlive: TColor = 0x008080;
const clOlivedrab: TColor = 0x238E6B;
const clOrange: TColor = 0x00A5FF;
const clOrangered: TColor = 0x0045FF;
const clOrchid: TColor = 0xD670DA;
const clPalegoldenrod: TColor = 0xAAE8EE;
const clPalegreen: TColor = 0x98FB98;
const clPaleturquoise: TColor = 0xEEEEAF;
const clPalevioletred: TColor = 0x9370DB;
const clPapayawhip: TColor = 0xD5EFFF;
const clPeachpuff: TColor = 0xB9DAFF;
const clPeru: TColor = 0x3F85CD;
const clPink: TColor = 0xCBC0FF;
const clPlum: TColor = 0xDDA0DD;
const clPowderblue: TColor = 0xE6E0B0;
const clPurple: TColor = 0x800080;
const clRed: TColor = 0x0000FF;
const clRosybrown: TColor = 0x8F8FBC;
const clRoyalblue: TColor = 0xE16941;
const clSaddlebrown: TColor = 0x13458B;
const clSalmon: TColor = 0x7280FA;
const clSandybrown: TColor = 0x60A4F4;
const clSeagreen: TColor = 0x578B2E;
const clSeashell: TColor = 0xEEF5FF;
const clSienna: TColor = 0x2D52A0;
const clSilver: TColor = 0xC0C0C0;
const clSkyblue: TColor = 0xEBCE87;
const clSlateblue: TColor = 0xCD5A6A;
const clSlategray: TColor = 0x908070;
const clSlategrey: TColor = 0x908070;
const clSnow: TColor = 0xFAFAFF;
const clSpringgreen: TColor = 0x7FFF00;
const clSteelblue: TColor = 0xB48246;
const clTan: TColor = 0x8CB4D2;
const clTeal: TColor = 0x808000;
const clThistle: TColor = 0xD8BFD8;
const clTomato: TColor = 0x4763FF;
const clTurquoise: TColor = 0xD0E040;
const clViolet: TColor = 0xEE82EE;
const clWheat: TColor = 0xB3DEF5;
const clWhite: TColor = 0xFFFFFF;
const clWhitesmoke: TColor = 0xF5F5F5;
const clYellow: TColor = 0x00FFFF;
const clYellowgreen: TColor = 0x32CD9A;
const clBtnFace: TColor = 0xFF00000F;
const clNull: TColor = 0x00000000;

// Virtual Keys, Standard Set
const vkLButton: Char = 0x01; // 1
const vkRButton: Char = 0x02; // 2
const vkCancel: Char = 0x03; // 3
const vkMButton: Char = 0x04; // 4
const vkXButton1: Char = 0x05; // 5
const vkXButton2: Char = 0x06; // 6
const vkBack: Char = 0x08; // 8
const vkTab: Char = 0x09; // 9
const vkLineFeed: Char = 0x0A; // 10
const vkClear: Char = 0x0C; // 12
const vkReturn: Char = 0x0D; // 13
const vkShift: Char = 0x10; // 16
const vkControl: Char = 0x11; // 17
const vkMenu: Char = 0x12; // 18
const vkPause: Char = 0x13; // 19
const vkCapital: Char = 0x14; // 20
const vkKana: Char = 0x15; // 21
const vkHangul: Char = 0x15; // 21
const vkJunja: Char = 0x17; // 23
const vkFinal: Char = 0x18; // 24
const vkHanja: Char = 0x19; // 25
const vkKanji: Char = 0x19; // 25
const vkConvert: Char = 0x1C; // 28
const vkNonConvert: Char = 0x1D; // 29
const vkAccept: Char = 0x1E; // 30
const vkModeChange: Char = 0x1F; // 31
const vkEscape: Char = 0x1B; // 27
const vkSpace: Char = 0x20; // 32
const vkPrior: Char = 0x21; // 33
const vkNext: Char = 0x22; // 34
const vkEnd: Char = 0x23; // 35
const vkHome: Char = 0x24; // 36
const vkLeft: Char = 0x25; // 37
const vkUp: Char = 0x26; // 38
const vkRight: Char = 0x27; // 39
const vkDown: Char = 0x28; // 40
const vkSelect: Char = 0x29; // 41
const vkPrint: Char = 0x2A; // 42
const vkExecute: Char = 0x2B; // 43
const vkSnapshot: Char = 0x2C; // 44
const vkInsert: Char = 0x2D; // 45
const vkDelete: Char = 0x2E; // 46
const vkHelp: Char = 0x2F; // 47

// vk0 thru vk9 are the same as ASCII &#39;0&#39; thru &#39;9&#39; (0x30 - 0x39)
const vk0: Char = 0x30; // 48
const vk1: Char = 0x31; // 49
const vk2: Char = 0x32; // 50
const vk3: Char = 0x33; // 51
const vk4: Char = 0x34; // 52
const vk5: Char = 0x35; // 53
const vk6: Char = 0x36; // 54
const vk7: Char = 0x37; // 55
const vk8: Char = 0x38; // 56
const vk9: Char = 0x39; // 57

// vkA thru vkZ are the same as ASCII &#39;A&#39; thru &#39;Z&#39; (0x41 - 0x5A)
const vkA: Char = 0x41; // 65
const vkB: Char = 0x42; // 66
const vkC: Char = 0x43; // 67
const vkD: Char = 0x44; // 68
const vkE: Char = 0x45; // 69
const vkF: Char = 0x46; // 70
const vkG: Char = 0x47; // 71
const vkH: Char = 0x48; // 72
const vkI: Char = 0x49; // 73
const vkJ: Char = 0x4A; // 74
const vkK: Char = 0x4B; // 75
const vkL: Char = 0x4C; // 76
const vkM: Char = 0x4D; // 77
const vkN: Char = 0x4E; // 78
const vkO: Char = 0x4F; // 79
const vkP: Char = 0x50; // 80
const vkQ: Char = 0x51; // 81
const vkR: Char = 0x52; // 82
const vkS: Char = 0x53; // 83
const vkT: Char = 0x54; // 84
const vkU: Char = 0x55; // 85
const vkV: Char = 0x56; // 86
const vkW: Char = 0x57; // 87
const vkX: Char = 0x58; // 88
const vkY: Char = 0x59; // 89
const vkZ: Char = 0x5A; // 90
const vkLWin: Char = 0x5B; // 91
const vkRWin: Char = 0x5C; // 92
const vkApps: Char = 0x5D; // 93
const vkSleep: Char = 0x5F; // 95
const vkNumpad0: Char = 0x60; // 96
const vkNumpad1: Char = 0x61; // 97
const vkNumpad2: Char = 0x62; // 98
const vkNumpad3: Char = 0x63; // 99
const vkNumpad4: Char = 0x64; // 100
const vkNumpad5: Char = 0x65; // 101
const vkNumpad6: Char = 0x66; // 102
const vkNumpad7: Char = 0x67; // 103
const vkNumpad8: Char = 0x68; // 104
const vkNumpad9: Char = 0x69; // 105
const vkMultiply: Char = 0x6A; // 106
const vkAdd: Char = 0x6B; // 107
const vkSeparator: Char = 0x6C; // 108
const vkSubtract: Char = 0x6D; // 109
const vkDecimal: Char = 0x6E; // 110
const vkDivide: Char = 0x6F; // 111
const vkF1: Char = 0x70; // 112
const vkF2: Char = 0x71; // 113
const vkF3: Char = 0x72; // 114
const vkF4: Char = 0x73; // 115
const vkF5: Char = 0x74; // 116
const vkF6: Char = 0x75; // 117
const vkF7: Char = 0x76; // 118
const vkF8: Char = 0x77; // 119
const vkF9: Char = 0x78; // 120
const vkF10: Char = 0x79; // 121
const vkF11: Char = 0x7A; // 122
const vkF12: Char = 0x7B; // 123
const vkF13: Char = 0x7C; // 124
const vkF14: Char = 0x7D; // 125
const vkF15: Char = 0x7E; // 126
const vkF16: Char = 0x7F; // 127
const vkF17: Char = 0x80; // 128
const vkF18: Char = 0x81; // 129
const vkF19: Char = 0x82; // 130
const vkF20: Char = 0x83; // 131
const vkF21: Char = 0x84; // 132
const vkF22: Char = 0x85; // 133
const vkF23: Char = 0x86; // 134
const vkF24: Char = 0x87; // 135
const vkCamera: Char = 0x88; // 136
const vkHardwareBack: Char = 0x89; // 137
const vkNumLock: Char = 0x90; // 144
const vkScroll: Char = 0x91; // 145
const vkLShift: Char = 0xA0; // 160
const vkRShift: Char = 0xA1; // 161
const vkLControl: Char = 0xA2; // 162
const vkRControl: Char = 0xA3; // 163
const vkLMenu: Char = 0xA4; // 164
const vkRMenu: Char = 0xA5; // 165
const vkBrowserBack: Char = 0xA6; // 166
const vkBrowserForward: Char = 0xA7; // 167
const vkBrowserRefresh: Char = 0xA8; // 168
const vkBrowserStop: Char = 0xA9; // 169
const vkBrowserSearch: Char = 0xAA; // 170
const vkBrowserFavorites: Char = 0xAB; // 171
const vkBrowserHome: Char = 0xAC; // 172
const vkVolumeMute: Char = 0xAD; // 173
const vkVolumeDown: Char = 0xAE; // 174
const vkVolumeUp: Char = 0xAF; // 175
const vkMediaNextTrack: Char = 0xB0; // 176
const vkMediaPrevTrack: Char = 0xB1; // 177
const vkMediaStop: Char = 0xB2; // 178
const vkMediaPlayPause: Char = 0xB3; // 179
const vkLaunchMail: Char = 0xB4; // 180
const vkLaunchMediaSelect: Char = 0xB5; // 181
const vkLaunchApp1: Char = 0xB6; // 182
const vkLaunchApp2: Char = 0xB7; // 183
const vkSemicolon: Char = 0xBA; // 186
const vkEqual: Char = 0xBB; // 187
const vkComma: Char = 0xBC; // 188
const vkMinus: Char = 0xBD; // 189
const vkPeriod: Char = 0xBE; // 190
const vkSlash: Char = 0xBF; // 191
const vkTilde: Char = 0xC0; // 192
const vkLeftBracket: Char = 0xDB; // 219
const vkBackslash: Char = 0xDC; // 220
const vkRightBracket: Char = 0xDD; // 221
const vkQuote: Char = 0xDE; // 222
const vkPara: Char = 0xDF; // 223
const vkOem102: Char = 0xE2; // 226
const vkIcoHelp: Char = 0xE3; // 227
const vkIco00: Char = 0xE4; // 228
const vkProcessKey: Char = 0xE5; // 229
const vkIcoClear: Char = 0xE6; // 230
const vkPacket: Char = 0xE7; // 231
const vkAttn: Char = 0xF6; // 246
const vkCrsel: Char = 0xF7; // 247
const vkExsel: Char = 0xF8; // 248
const vkErEof: Char = 0xF9; // 249
const vkPlay: Char = 0xFA; // 250
const vkZoom: Char = 0xFB; // 251
const vkNoname: Char = 0xFC; // 252
const vkPA1: Char = 0xFD; // 253
const vkOemClear: Char = 0xFE; // 254
const vkNone: Char = 0xFF; // 255

// MessageBox or MessageDlg 返回值
const idOK: u8 = 1;
const idCancel: u8 = 2;
const idAbort: u8 = 3;
const idRetry: u8 = 4;
const idIgnore: u8 = 5;
const idYes: u8 = 6;
const idNo: u8 = 7;
const idClose: u8 = 8;
const idHelp: u8 = 9;
const idTryAgain: u8 = 10;
const idContinue: u8 = 11;
const mrNone: u8 = 0;
const mrOk: u8 = idOK;
const mrCancel: u8 = idCancel;
const mrAbort: u8 = idAbort;
const mrRetry: u8 = idRetry;
const mrIgnore: u8 = idIgnore;
const mrYes: u8 = idYes;
const mrNo: u8 = idNo;
const mrClose: u8 = idClose;
const mrHelp: u8 = idHelp;
const mrTryAgain: u8 = idTryAgain;
const mrContinue: u8 = idContinue;
const mrAll: u8 = mrContinue + 1;
const mrNoToAll: u8 = mrAll + 1;
const mrYesToAll: u8 = mrNoToAll + 1;

// Predefined Clipboard Formats
const CF_TEXT: u8 = 1;
const CF_BITMAP: u8 = 2;
const CF_METAFILEPICT: u8 = 3;
const CF_SYLK: u8 = 4;
const CF_DIF: u8 = 5;
const CF_TIFF: u8 = 6;
const CF_OEMTEXT: u8 = 7;
const CF_DIB: u8 = 8;
const CF_PALETTE: u8 = 9;
const CF_PENDATA: u8 = 10;
const CF_RIFF: u8 = 11;
const CF_WAVE: u8 = 12;
const CF_UNICODETEXT: u8 = 13;
const CF_ENHMETAFILE: u8 = 14;
const CF_HDROP: u8 = 15;
const CF_LOCALE: u8 = 0x10;

// 光标定义
const crHigh: TCursor = 0;
const crDefault: TCursor = 0;
const crNone: TCursor = -1;
const crArrow: TCursor = -2;
const crCross: TCursor = -3;
const crIBeam: TCursor = -4;
const crSize: TCursor = -22;
const crSizeNESW: TCursor = -6; // diagonal north east - south west
const crSizeNS: TCursor = -7;
const crSizeNWSE: TCursor = -8;
const crSizeWE: TCursor = -9;
const crSizeNW: TCursor = -23;
const crSizeN: TCursor = -24;
const crSizeNE: TCursor = -25;
const crSizeW: TCursor = -26;
const crSizeE: TCursor = -27;
const crSizeSW: TCursor = -28;
const crSizeS: TCursor = -29;
const crSizeSE: TCursor = -30;
const crUpArrow: TCursor = -10;
const crHourGlass: TCursor = -11;
const crDrag: TCursor = -12;
const crNoDrop: TCursor = -13;
const crHSplit: TCursor = -14;
const crVSplit: TCursor = -15;
const crMultiDrag: TCursor = -16;
const crSQLWait: TCursor = -17;
const crNo: TCursor = -18;
const crAppStart: TCursor = -19;
const crHelp: TCursor = -20;
const crHandPoint: TCursor = -21;
const crSizeAll: TCursor = -22;
const crLow: TCursor = -30;
